### ISSUE TITLE
"Invalid type" exception with spredsheet data in FreeCAD 0.19

### ISSUE THREAD

**Issue by shyblower** [DeepSOIC/Lattice2#45] opened 2020-04-26 14:03 UTC
When I try to use a value from a FC spreadsheet for the "Count" property of e.g. the PolarArray then the following exception is thrown:
`<Exception> Invalid type 'l'
in property binding 'Count'
11942.7 <App> Document.cpp(3693): Failed to recompute ArrayTest#PolarArray: Invalid type 'l'
in property binding 'Count'`

it does work in FC 0.18, though.

I've also figured out a hack to work around this issue in FC 0.19. When I add a unit symbol like "mm" at the end of the number in the spreadsheet, then I can use it for the "Count" property. It will only issue a warning that the unit symbol will be stripped.

OS: Gentoo/Linux (GNOME/gnome)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.20655 (Git) AppImage
Build type: Release
Branch: master
Hash: e8e67e8c5ebbc9f9ed9ea67aba5b891969595ece
Python version: 3.8.2
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United States (en_US)

**Comment by DeepSOIC** [comment] 2020-04-26 14:23
I can reproduce. Seems to be a freecad bug. I get this error:

`<Exception> Invalid type 'long'
in property binding 'Count'`

if I set a fractional value like 4.000000001, the error disappears.

**Comment by shyblower** [comment] 2020-04-26 14:25
Yes, fractional values also work for me, just tried :)

**Comment by DeepSOIC** [comment] 2020-04-26 22:24
https://forum.freecadweb.org/viewtopic.php?f=3&t=45720

**Comment by DeepSOIC** [comment] 2020-04-27 11:12
Should be fixed since FC 0.19.20814

**Closed** 2020-04-27 11:13 UTC
Labels: freecad bug
